name: On Push

on: [ push ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Restore tools
        run: dotnet tool restore
      - name: Restore dependencies
        run: dotnet restore
      - name: Run F# linter
        run: dotnet fsharplint lint OpenApi.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore
